.PHONY: clean All

All:
	@echo "----------Building project:[ OOPPractice1 - Debug ]----------"
	@cd "OOPPractice1" && "$(MAKE)" -f  "OOPPractice1.mk"
clean:
	@echo "----------Cleaning project:[ OOPPractice1 - Debug ]----------"
	@cd "OOPPractice1" && "$(MAKE)" -f  "OOPPractice1.mk" clean
